name: Mido

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'Device'
          default: 'mido'
          required: true
      repo:
          description: 'Kernel source'
          default: 'https://github.com/malkist01/su-mid.git'
          required: true
      branch:
          description: 'Kernel source branch'
          default: '14'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7596553794:AAGoeg4VypmUfBqfUML5VWt5mjivN5-3ah8'
          required: true
      chat_id:
          description: 'Telegram chat id'
          default: '-1002287610863'
          required: true
          
env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  GKI: ${{ github.event.inputs.gki }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-24.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "malkist"
          git config --global user.email "malkist01@gmail.com"
          df -h
          ld --version
          gcc -v
          ar --version
          sudo apt update
          sudo apt install -y bc cpio flex bison aptitude git python-is-python3 tar aria2 perl wget curl lz4 libssl-dev device-tree-compiler
          sudo apt install -y zstd

      - name: Building kernel...
        run: |
          if [ "${DEVICE}" = "mido" ]; then
            wget https://raw.githubusercontent.com/malkist01/Tele/main/mido.sh
            bash mido.sh
          else
            echo "Device not supported yet"
          fi
